module.exports = [
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "3:36",
    DepartureTime: "/Date(1621802160000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "3:46",
    DepartureTime: "/Date(1621802760000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "3:56",
    DepartureTime: "/Date(1621803360000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "4:06",
    DepartureTime: "/Date(1621803960000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "4:16",
    DepartureTime: "/Date(1621804560000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "4:26",
    DepartureTime: "/Date(1621805160000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "4:36",
    DepartureTime: "/Date(1621805760000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "4:46",
    DepartureTime: "/Date(1621806360000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "4:56",
    DepartureTime: "/Date(1621806960000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "5:06",
    DepartureTime: "/Date(1621807560000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "5:16",
    DepartureTime: "/Date(1621808160000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "5:26",
    DepartureTime: "/Date(1621808760000-0500)/",
    Description: "to Mpls-Target Field",
    Gate: null,
    Route: "Blue",
    RouteDirection: "NB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
];
