module.exports = [
  {
    Actual: true,
    BlockNumber: 0,
    DepartureText: "3 Min",
    DepartureTime: "/Date(1621795380000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: true,
    BlockNumber: 0,
    DepartureText: "12 Min",
    DepartureTime: "/Date(1621795920000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "2:01",
    DepartureTime: "/Date(1621796460000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "2:11",
    DepartureTime: "/Date(1621797060000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "2:21",
    DepartureTime: "/Date(1621797660000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "2:31",
    DepartureTime: "/Date(1621798260000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "2:41",
    DepartureTime: "/Date(1621798860000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "2:51",
    DepartureTime: "/Date(1621799460000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "3:01",
    DepartureTime: "/Date(1621800060000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "3:11",
    DepartureTime: "/Date(1621800660000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "3:21",
    DepartureTime: "/Date(1621801260000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
  {
    Actual: false,
    BlockNumber: 0,
    DepartureText: "3:31",
    DepartureTime: "/Date(1621801860000-0500)/",
    Description: "to Mall of America",
    Gate: null,
    Route: "Blue",
    RouteDirection: "SB",
    Terminal: null,
    VehicleHeading: 0,
    VehicleLatitude: 0,
    VehicleLongitude: 0,
  },
];
